# Generated by Django 5.2.4 on 2025-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_choice_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='polaroid',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
