# Generated by Django 5.2.4 on 2025-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_polaroid_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
