# Generated by Django 5.2.4 on 2025-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_country_flag_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='music_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
    ]
