# Generated by Django 5.2.4 on 2025-08-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_country_music_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='music_file',
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='Example: germany_theme.mp3', max_length=100)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
    ]
